# Generated by Django 2.2 on 2021-06-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smt_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smt_report',
            name='margin_budget',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smt_report',
            name='sales_budget',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
