# Generated by Django 2.2 on 2021-06-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra_table', '0002_auto_20210621_0826'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invertory',
            new_name='Inventory',
        ),
    ]
