# Generated by Django 2.2 on 2021-06-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='stores',
        ),
        migrations.AddField(
            model_name='members',
            name='eff_new',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='eff_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='label',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
